Repository alyzadiaz/spacebook, pull requests merged in 2021-04, with the labels that each got.

#40 Danielle
  HTML/home.css
  HTML/home.html
  HTML/roadster_detail.html
  HTML/starlink_detail.html
  JAVASCRIPT/roadster_detail.js
  JAVASCRIPT/starlink_detail.js
  RESOURCES/Roadster.png
  RESOURCES/Starlink.png
  RESOURCES/Starlink_constellation.jpg
  RESOURCES/Starman.jpg
  RESOURCES/fh_performance.webm
Labels: Interact with graphic, Task, UI

#43 Site-wide CSS modifications
  HTML/mission.css
  HTML/mission.html
  HTML/mission_detail.css
  HTML/roadster_detail.html
  HTML/rockets.css
  HTML/rockets.html
  HTML/starlink_detail.html
  JAVASCRIPT/mission.js
  JAVASCRIPT/roadster_detail.js
  JAVASCRIPT/starlink_detail.js
  RESOURCES/stars.jpg
Labels: Interact with graphic, Search bar, UI, design

#45 Search bar and Logo
  HTML/home.css
  HTML/home.html
  HTML/mission.css
  HTML/mission.html
  HTML/mission_detail.css
  HTML/roadster_detail.html
  HTML/rockets.css
  HTML/rockets.html
  HTML/starlink_detail.html
  JAVASCRIPT/mission.js
  JAVASCRIPT/rockets.js
  RESOURCES/logo.png
Labels: Search bar, Task, UI, design

#48 Create spacebook-home.PNG
  RESOURCES/PROJECT IMAGES/spacebook-home.PNG
Labels: documentation

#50 Adding first test case
  JAVASCRIPT/test.java
Labels: Testing
